title:              Renka's Blog
email:              connect.rayce@gmail.com
description:        Pianist, web designer and high school student.
author:             Renka 2021
baseurl:            "/"
url:                "https://renquashy.ml"

# Social Profiles
twitter_username:   ichigomochi1220
github_username:    
facebook_username:  StartBootstrap
instagram_username: 
linkedin_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-193963560-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
